config/routes.rb
Rails.application.routes.draw do
  get "restaurants", to: "restaurants#index"
  get "restaurants/new", to: "restaurants#new"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  get "restaurants/:id/edit", to: "restaurants#edit", as: :restaurant_edit

  post "restaurants", to: "restaurants#create"
  patch "restaurants/:id", to: "restaurants#update"
  delete "restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurant_path(restaurant)
  end

  def edit; end

  def update
    @restaurant.update(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit submit_action %>
<% end %>

app/views/restaurants/edit.html.erb
<h1><%= @restaurant.name %>:<em>edit details</em></h1>
<hr>
<div>
  <%= render 'form', {restaurant: @restaurant, submit_action: "💾 Save"} %>
</div>
<%= link_to "❌ Cancel", restaurant_path %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>
<p><%= link_to "✨ Add new restaurant", restaurants_new_path %></p>
<% @restaurants.each do |restaurant| %>
  <div>
    <div>
      <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
      <p><%= restaurant.address %></p>
    </div>
      <p>Rating: <%= restaurant.rating %></p>
      <p>id: <%= restaurant.id %></p>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<div>
  <%= render 'form', {restaurant: @restaurant, submit_action: "➕ Add"} %>
</div>

<%= link_to "❌ Cancel", restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p>(<%= "⭐" * @restaurant.rating %>)</p>

<p><%= @restaurant.address %></p>

<p><%= link_to "↩️ Back to all restaurants", restaurants_path %></p>
<%= link_to "📝 Edit", restaurant_edit_path %>
<%= link_to "🗑️ Delete",
  restaurant_path(@restaurant),
  data: {turbo_method: :delete, turbo_confirm: "Delete this restaurant?"}
%>